name: CI Pipeline

on: [push]

jobs:
    jest:
        name: Jest Tests
        runs-on: ubuntu-latest
        steps:
            -   name: Clone Code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4

            -   name: Install Dependencies
                run: make dev -B

            -   name: Install Admin Dependencies
                run: make admin -B

            -   name: Run Jest
                run: make jest -B

    eslint:
        name: ESLint
        runs-on: ubuntu-latest
        needs: jest
        steps:
            -   name: Clone Code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4

            -   name: Install Dependencies
                run: make dev -B

            -   name: Run ESLint
                run: make eslint -B

    # ------------------------------------------------------------------------------------------------------------------------

    php_checks:
        name: PHP Syntax Checks
        runs-on: ubuntu-latest
        steps:
            -   name: Clone Code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4

            -   name: PHP Syntax Checks
                run: make phpcheck -B

    phpunit:
        name: Unit Tests | PHP ${{ matrix.php }}
        needs: php_checks
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.4' ]
        steps:
            - name: Clone Code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Install Dependencies
              run: make dev -B

            - name: Run PHPUnit
              run: make phpunit -B

    infection:
        name: Mutation Tests | PHP ${{ matrix.php }}
        needs: phpunit
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.4' ]
        steps:
            - name: Clone Code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Install Dependencies
              run: make dev -B

            - name: Run Infection
              run: make infection -B

    phpcsfixer:
        name: PHP CS Fixer
        needs: infection
        runs-on: ubuntu-latest
        steps:

            - name: Clone Code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4

            - name: Install Dependencies
              run: make dev -B

            - name: Run PHP CS Fixer
              run: make csfix -B
